#!/usr/bin/env python

# This file is part of Fleeting Password Manager (FleetingPM).
# Copyright (C) 2011 Jussi Lind <jussi.lind@iki.fi>
#
# FleetingPM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# FleetingPM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FleetingPM. If not, see <http://www.gnu.org/licenses/>.

import os, sys

try:
    from fleetingpmlib import MainWindow
except ImportError:
    sys.stderr.write("ERROR!!: Cannot find fleetingpmlib\n")
    sys.exit(1)

try:
    from PySide import QtCore, QtGui
except ImportError:
    sys.stderr.write("ERROR!!: Cannot find PySide. You must have python-pyside installed.\n")
    sys.exit(1)

def main(argv):
    app = QtGui.QApplication(argv)
    mainWindow = MainWindow.MainWindow(None)
    mainWindow.show()
    app.exec_()

if __name__ == '__main__':
    main(sys.argv)

