#!/bin/bash

QMAKE=qmake-qt4
TAR=tar
LRELEASE=lrelease
NUM_CPUS=$(cat /proc/cpuinfo | grep processor | wc -l)

# Package naming

EXEC=fleetingpm
NAME=fleetingpm
VERSION=2.8.3
ARCH=linux-x86_64
QT=qt4

# Build

./configure && make -j$NUM_CPUS || exit -1

# Install to packaging dir

PACKAGE_PATH=$NAME-$VERSION-$ARCH-$QT
rm -rf $PACKAGE_PATH
mkdir $PACKAGE_PATH

cp -v ./$EXEC $PACKAGE_PATH/$EXEC.x || exit -1

TEXT_FILES="AUTHORS CHANGELOG COPYING README"
cp -v $TEXT_FILES $PACKAGE_PATH || exit -1

# Copy dependecies

cp -v $(ldd $PACKAGE_PATH/$EXEC.x | grep "/usr/lib" | grep -v libX | awk '{print $3}') $PACKAGE_PATH

# Additional libs

LIBS=png
for lib in $LIBS; do
cp -v $(ldd $PACKAGE_PATH/$EXEC.x | grep $lib | grep -v libX | awk '{print $3}') $PACKAGE_PATH
done

# Copy Qt plugins

cp -r -v $($QMAKE -query | grep QT_INSTALL_PLUGINS | cut -d: -f2) $PACKAGE_PATH

# Create qt.conf (this is needed for possible plugin conflicts)

QTCONF=$PACKAGE_PATH/qt.conf
echo "[Paths]" > $QTCONF
echo "Plugins = '.'" >> $QTCONF

# Create start script for the app

SCRIPT=$PACKAGE_PATH/$EXEC
echo "#!/bin/sh" > $SCRIPT
echo "LD_LIBRARY_PATH=. ./$EXEC.x" >> $SCRIPT
chmod 755 $SCRIPT

# Create tgz archive

TGZ_ARCHIVE=$PACKAGE_PATH.tar.gz
rm -f $TGZ_ARCHIVE
$TAR czvf $TGZ_ARCHIVE $PACKAGE_PATH

ls -ltr

echo "Done."

