// This file is part of Fleeting Password Manager (Fleetingpm).
// Copyright (C) 2011 Jussi Lind <jussi.lind@iki.fi>
//
// Fleetingpm is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// Fleetingpm is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Fleetingpm. If not, see <http://www.gnu.org/licenses/>.
//

#include <QFile>
#include <QDate>
#include <QTextStream>
#include <QDomDocument>
#include <QDomElement>

#include "loginio.h"
#include "config.h"

bool LoginIO::importLogins(LoginIO::LoginList & rLogins, QString fileName)
{
    QDomDocument doc;

    QFile file(fileName);
    if (!file.open(QIODevice::ReadOnly))
    {
        return false;
    }

    if (!doc.setContent(&file))
    {
        file.close();
        return false;
    }

    file.close();

    QDomElement root = doc.documentElement();
    QDomNode    node = root.firstChild();

    rLogins.clear();

    while(!node.isNull())
    {
        QDomElement tag = node.toElement();
        if(!tag.isNull())
        {
            if (tag.nodeName() == "login")
            {
                QString url    = tag.attribute("url", "");
                QString user   = tag.attribute("user", "");
                int     length = tag.attribute("length", 0).toInt();

                rLogins << LoginData(url, user, length);
            }

            node = node.nextSibling();
        }
    }

    return true;
}

bool LoginIO::exportLogins(LoginIO::LoginList logins, QString fileName)
{
    // Create content
    QDomDocument doc;
    QDomComment header = doc.createComment(QString("Generated by ") + Config::NAME + " on " +
                                           QDate::currentDate().toString());
    doc.appendChild(header);

    QDomElement root = doc.createElement("logins");
    root.setAttribute("version", Config::VERSION);
    doc.appendChild(root);

    for (int i = 0; i < logins.count(); i++)
    {
        QDomElement loginTag = doc.createElement("login");
        loginTag.setAttribute("url",    logins.at(i).url());
        loginTag.setAttribute("user",   logins.at(i).userName());
        loginTag.setAttribute("length", logins.at(i).passwordLength());
        root.appendChild(loginTag);
    }

    QFile file(fileName);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text))
    {
        QTextStream out(&file);
        out << doc.toString();
        file.close();
        return true;
    }

    return false;
}
